export const seasons = [
  {
    "year": 2025,
    "leagueRecord": "11-3",
    "leagueFinish": "2nd",
    "overallRecord": "14-9",
    "playoffResults": "Districts: 3rd Round",
    "isLeagueChampion": false,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2024,
    "leagueRecord": "8-4",
    "leagueFinish": "2nd",
    "overallRecord": "16-9",
    "playoffResults": "State: 1st Round",
    "isLeagueChampion": false,
    "isStateAppearance": true,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2023,
    "leagueRecord": "12-0",
    "leagueFinish": "1st",
    "overallRecord": "25-3",
    "playoffResults": "Final Four: 3rd Place",
    "isLeagueChampion": true,
    "isStateAppearance": true,
    "isFinalFour": true,
    "isDistrictChamp": false
  },
  {
    "year": 2022,
    "leagueRecord": "8-4",
    "leagueFinish": "2nd",
    "overallRecord": "16-7",
    "playoffResults": "State: 1st Round",
    "isLeagueChampion": false,
    "isStateAppearance": true,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2021,
    "leagueRecord": "11-1",
    "leagueFinish": "1st",
    "overallRecord": "16-1",
    "playoffResults": "No playoffs due to Covid",
    "isLeagueChampion": true,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2020,
    "leagueRecord": "-",
    "leagueFinish": "-",
    "overallRecord": "-",
    "playoffResults": "-",
    "isLeagueChampion": false,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2019,
    "leagueRecord": "11-3",
    "leagueFinish": "1st",
    "overallRecord": "17-9",
    "playoffResults": "State: 2nd Round",
    "isLeagueChampion": true,
    "isStateAppearance": true,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2018,
    "leagueRecord": "14-0",
    "leagueFinish": "1st",
    "overallRecord": "20-4",
    "playoffResults": "State: 1st Round",
    "isLeagueChampion": true,
    "isStateAppearance": true,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2017,
    "leagueRecord": "9-5",
    "leagueFinish": "4th",
    "overallRecord": "16-8",
    "playoffResults": "State: 1st Round",
    "isLeagueChampion": false,
    "isStateAppearance": true,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2016,
    "leagueRecord": "8-4",
    "leagueFinish": "3rd",
    "overallRecord": "18-8",
    "playoffResults": "Districts: 3rd Round",
    "isLeagueChampion": false,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2015,
    "leagueRecord": "6-6",
    "leagueFinish": "5th",
    "overallRecord": "15-10",
    "playoffResults": "Districts: 3rd Round",
    "isLeagueChampion": false,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2014,
    "leagueRecord": "12-4",
    "leagueFinish": "2nd",
    "overallRecord": "16-8",
    "playoffResults": "Districts: 4th Round",
    "isLeagueChampion": false,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2013,
    "leagueRecord": "10-6",
    "leagueFinish": "4th",
    "overallRecord": "13-8",
    "playoffResults": "Districts: 1st Round",
    "isLeagueChampion": false,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2012,
    "leagueRecord": "12-4",
    "leagueFinish": "2nd",
    "overallRecord": "17-7",
    "playoffResults": "State: 2nd Round, District Champs",
    "isLeagueChampion": false,
    "isStateAppearance": true,
    "isFinalFour": false,
    "isDistrictChamp": true
  },
  {
    "year": 2011,
    "leagueRecord": "15-1",
    "leagueFinish": "1st",
    "overallRecord": "20-3",
    "playoffResults": "State: 1st Round",
    "isLeagueChampion": true,
    "isStateAppearance": true,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2010,
    "leagueRecord": "10-6",
    "leagueFinish": "3rd",
    "overallRecord": "15-8",
    "playoffResults": "Districts",
    "isLeagueChampion": false,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2009,
    "leagueRecord": "15-1",
    "leagueFinish": "1st",
    "overallRecord": "22-3",
    "playoffResults": "Final Four: 3rd Place",
    "isLeagueChampion": true,
    "isStateAppearance": true,
    "isFinalFour": true,
    "isDistrictChamp": false
  },
  {
    "year": 2008,
    "leagueRecord": "11-3",
    "leagueFinish": "2nd",
    "overallRecord": "16-7",
    "playoffResults": "State: 1st Round",
    "isLeagueChampion": false,
    "isStateAppearance": true,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2007,
    "leagueRecord": "13-1",
    "leagueFinish": "1st",
    "overallRecord": "23-3",
    "playoffResults": "Final Four: 3rd Place",
    "isLeagueChampion": true,
    "isStateAppearance": true,
    "isFinalFour": true,
    "isDistrictChamp": false
  },
  {
    "year": 2006,
    "leagueRecord": "15-1",
    "leagueFinish": "2nd",
    "overallRecord": "22-5",
    "playoffResults": "Final Four: 4th Place, Regional Champs, District Champs",
    "isLeagueChampion": false,
    "isStateAppearance": true,
    "isFinalFour": true,
    "isDistrictChamp": true
  },
  {
    "year": 2005,
    "leagueRecord": "10-6",
    "leagueFinish": "3rd",
    "overallRecord": "13-9",
    "playoffResults": "Districts: 2nd Round",
    "isLeagueChampion": false,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2004,
    "leagueRecord": "9-7",
    "leagueFinish": "6th",
    "overallRecord": "12-9",
    "playoffResults": "-",
    "isLeagueChampion": false,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2003,
    "leagueRecord": "10-6",
    "leagueFinish": "3rd",
    "overallRecord": "19-7",
    "playoffResults": "Final Four: 3rd Place",
    "isLeagueChampion": false,
    "isStateAppearance": true,
    "isFinalFour": true,
    "isDistrictChamp": false
  },
  {
    "year": 2002,
    "leagueRecord": "7-9",
    "leagueFinish": "7th",
    "overallRecord": "8-10",
    "playoffResults": "-",
    "isLeagueChampion": false,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2001,
    "leagueRecord": "6-10",
    "leagueFinish": "7th",
    "overallRecord": "8-12",
    "playoffResults": "-",
    "isLeagueChampion": false,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 2000,
    "leagueRecord": "5-11",
    "leagueFinish": "7th",
    "overallRecord": "5-20",
    "playoffResults": "-",
    "isLeagueChampion": false,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 1999,
    "leagueRecord": "3-11",
    "leagueFinish": "8th",
    "overallRecord": "6-12",
    "playoffResults": "-",
    "isLeagueChampion": false,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 1998,
    "leagueRecord": "2-12",
    "leagueFinish": "7th",
    "overallRecord": "4-15",
    "playoffResults": "-",
    "isLeagueChampion": false,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 1997,
    "leagueRecord": "12-6 (2A)",
    "leagueFinish": "2nd",
    "overallRecord": "13-8",
    "playoffResults": "-",
    "isLeagueChampion": false,
    "isStateAppearance": false,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 1996,
    "leagueRecord": "15-3 (2A)",
    "leagueFinish": "2nd",
    "overallRecord": "16-4",
    "playoffResults": "State",
    "isLeagueChampion": false,
    "isStateAppearance": true,
    "isFinalFour": false,
    "isDistrictChamp": false
  },
  {
    "year": 1995,
    "leagueRecord": "16-2 (2A)",
    "leagueFinish": "1st",
    "overallRecord": "19-4",
    "playoffResults": "State",
    "isLeagueChampion": true,
    "isStateAppearance": true,
    "isFinalFour": false,
    "isDistrictChamp": false
  }
];
